const INITIAL_DATA = {
    people: [
        { id: "LKO", initials: "LKO", fullName: "Lukáš Kohout", group: "dev", maxCapacity: 100, active: true },
        { id: "RKO", initials: "RKO", fullName: "Roman Kožnar", group: "dev", maxCapacity: 100, active: true },
        { id: "FTI", initials: "FTI", fullName: "Filip Tichánek", group: "dev", maxCapacity: 100, active: true },
        { id: "MMA", initials: "MMA", fullName: "Martin Matouček", group: "dev", maxCapacity: 100, active: true },
        { id: "MJU", initials: "MJU", fullName: "Michal Juřina", group: "dev", maxCapacity: 100, active: true },
        { id: "JNE", initials: "JNE", fullName: "Jakub Němec", group: "dev", maxCapacity: 100, active: true },
        { id: "DBR", initials: "DBR", fullName: "Daniel Brabec", group: "dev", maxCapacity: 100, active: true },
        { id: "MLO", initials: "MLO", fullName: "Martin Losmann", group: "dev", maxCapacity: 100, active: true },
        { id: "PTO", initials: "PTO", fullName: "Petr Tobiáš", group: "dev", maxCapacity: 100, active: true },
        { id: "Hrabi", initials: "Hrabi", fullName: "Jakub Hrábek", group: "dev", maxCapacity: 100, active: true },
        { id: "OKO", initials: "OKO", fullName: "Otakar Kočka", group: "dev", maxCapacity: 100, active: true },
        { id: "VMY", initials: "VMY", fullName: "Vladimír Myšák", group: "dev", maxCapacity: 100, active: true },
        { id: "OPR", initials: "OPR", fullName: "Ondřej Průcha", group: "design", maxCapacity: 100, active: true },
        { id: "SNG", initials: "SNG", fullName: "Sall Nguyen", group: "design", maxCapacity: 100, active: true },
        { id: "LAB", initials: "LAB", fullName: "Ľubomír Abrinko", group: "design", maxCapacity: 100, active: true },
        { id: "JJE", initials: "JJE", fullName: "Jan Jelínek", group: "design", maxCapacity: 100, active: true },
        { id: "EPO", initials: "EPO", fullName: "Eduard Polúch", group: "design", maxCapacity: 100, active: true },
        { id: "JKA", initials: "JKA", fullName: "Jan Kalvoda", group: "pm", maxCapacity: 0, active: true },
        { id: "JVI", initials: "JVI", fullName: "Jiří Viták", group: "pm", maxCapacity: 0, active: true },
        { id: "DHA", initials: "DHA", fullName: "Dan Hamerník", group: "pm", maxCapacity: 0, active: true },
        { id: "JSV", initials: "JSV", fullName: "Jakub Svoboda", group: "pm", maxCapacity: 0, active: true },
        { id: "LMA", initials: "LMA", fullName: "Lukáš Malík", group: "pm", maxCapacity: 0, active: true },
        { id: "MIM", initials: "MIM", fullName: "Michal Málek", group: "pm", maxCapacity: 0, active: true }
    ],
    projects: [
        { id: "p1", name: "Up Gusto + Up Rekrea", status: "active", pmId: "JKA" },
        { id: "p2", name: "UP - B2B app", status: "active", pmId: "JKA" },
        { id: "p3", name: "UP Rekrea", status: "active", pmId: "" },
        { id: "p4", name: "Orea - Web", status: "active", pmId: "" },
        { id: "p5", name: "Orea - Nákupní portál", status: "active", pmId: "" },
        { id: "p6", name: "Bika", status: "active", pmId: "" },
        { id: "p7", name: "Bednar", status: "active", pmId: "" },
        { id: "p8", name: "SÚKL", status: "active", pmId: "" },
        { id: "p9", name: "GTS_ISIC", status: "active", pmId: "" },
        { id: "p10", name: "Veacom", status: "active", pmId: "" },
        { id: "p11", name: "MND_Bodyshop", status: "active", pmId: "" },
        { id: "p12", name: "MND_GIS", status: "active", pmId: "" },
        { id: "p13", name: "ČP_Balíkovna", status: "active", pmId: "" }
    ],
    assignments: []
};
